### ISSUE TITLE
Release Beta Version With FileBot 4.9.5 Beta

### ISSUE THREAD

**Issue by HarryMuscle** [jlesage/docker-filebot#71]
I was wondering if you'd be willing to release a beta version of this Docker container with FileBot 4.9.5 Beta.  It looks like FileBot 4.9.5 will bring some new functionality for scripting, especially related to TMDB.  It also requires a newer version of Java than what is bundled with this container and I noticed that the repo for the Java in this container hasn't released any new versions sine 2018 so I'm guessing a new source for the Java package will need to be used.  It's definitely shaping up to be a more major upgrade than the usual ones so I thought a beta release might prove useful.

**Comment by jlesage** [comment]
You are right.  This container is currently using the Java8 version of FileBot.  Unfortunately, for FileBot 4.9.5, this version works for CLI only.   The GUI no longer work.

The main reason why this container was sticking to Java 8 is because of a dependency on JavaFX.  The only Alpine Linux implementation of JFX is for Java 8.

However, I found a way to remove the JavaFX dependency.  So I will release an image with the current FileBot stable version (4.9.4) that runs with Java 17.  This should pave the way for FileBot 4.9.5.

**Comment by jlesage** [comment]
I'm also thinking into adding a mechanism that would allow people to use a beta version with the image.

**Comment by jlesage** [comment]
With the latest Docker image (v1.13.0), Java 17 is used to run FileBot.  We should not have any issue running 4.9.5 when officially released.

Also, you can now use the beta version by using the `USE_FILEBOT_BETA` variable.  See documentation for more details.
